<!doctype html>



  


<html class="theme-next mist use-motion" lang="zh-Hans">
<head>
  <!-- hexo-inject:begin --><!-- hexo-inject:end --><meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>



<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />












  
  
  <link href="/lib/fancybox/source/jquery.fancybox.css?v=2.1.5" rel="stylesheet" type="text/css" />




  
  
  
  

  
    
    
  

  

  

  

  

  
    
    
    <link href="//fonts.googleapis.com/css?family=Lato:300,300italic,400,400italic,700,700italic&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  






<link href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css" />

<link href="/css/main.css?v=5.1.0" rel="stylesheet" type="text/css" />


  <meta name="keywords" content="Java,异常处理," />





  <link rel="alternate" href="/atom.xml" title="Free Will" type="application/atom+xml" />




  <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico?v=5.1.0" />






<meta name="description" content="一、异常处理基础Java异常是一个描述在代码段中发生的异常（也就是出错）情况的对象。当异常情况发生，一个代表该异常的对象被创建并且在导致该错误的方法中被抛出（throw）。该方法可以选择自己处理异常或传递该异常。两种情况下，该异常被捕获（catch）并处理。异常可能是由Java运行时系统产生，或者是由你的手工代码产生。被Java抛出的异常与违反语言规范或超出Java执行环境限制的基本错误有关。手工">
<meta name="keywords" content="Java,异常处理">
<meta property="og:type" content="article">
<meta property="og:title" content="Java学习笔记（6）：异常处理">
<meta property="og:url" content="http://yoursite.com/2017/08/25/Java学习笔记（6）：异常处理/index.html">
<meta property="og:site_name" content="Free Will">
<meta property="og:description" content="一、异常处理基础Java异常是一个描述在代码段中发生的异常（也就是出错）情况的对象。当异常情况发生，一个代表该异常的对象被创建并且在导致该错误的方法中被抛出（throw）。该方法可以选择自己处理异常或传递该异常。两种情况下，该异常被捕获（catch）并处理。异常可能是由Java运行时系统产生，或者是由你的手工代码产生。被Java抛出的异常与违反语言规范或超出Java执行环境限制的基本错误有关。手工">
<meta property="og:locale" content="zh-Hans">
<meta property="og:updated_time" content="2019-07-30T10:51:50.996Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Java学习笔记（6）：异常处理">
<meta name="twitter:description" content="一、异常处理基础Java异常是一个描述在代码段中发生的异常（也就是出错）情况的对象。当异常情况发生，一个代表该异常的对象被创建并且在导致该错误的方法中被抛出（throw）。该方法可以选择自己处理异常或传递该异常。两种情况下，该异常被捕获（catch）并处理。异常可能是由Java运行时系统产生，或者是由你的手工代码产生。被Java抛出的异常与违反语言规范或超出Java执行环境限制的基本错误有关。手工">



<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Mist',
    sidebar: {"position":"left","display":"always","onmobile":true},
    fancybox: true,
    motion: true,
    duoshuo: {
      userId: '0',
      author: '博主'
    },
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>

<script data-ad-client="ca-pub-6293681360909288" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>









  <title> Java学习笔记（6）：异常处理 | Free Will </title><!-- hexo-inject:begin --><!-- hexo-inject:end -->
</head>

<body itemscope itemtype="http://schema.org/WebPage" lang="zh-Hans">

  



  <!-- hexo-inject:begin --><!-- hexo-inject:end --><script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?9a21041c6a1d47620a3a748589516274";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>









  
  
    
  

  <div class="container one-collumn sidebar-position-left page-post-detail ">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-meta ">
  

  <div class="custom-logo-site-title">
    <a href="/"  class="brand" rel="start">
      <span class="logo-line-before"><i></i></span>
      <span class="site-title">Free Will</span>
      <span class="logo-line-after"><i></i></span>
    </a>
  </div>
  <p class="site-subtitle"></p>
</div>

<div class="site-nav-toggle">
  <button>
    <span class="btn-bar"></span>
    <span class="btn-bar"></span>
    <span class="btn-bar"></span>
  </button>
</div>

<nav class="site-nav">
  

  
    <ul id="menu" class="menu">
      
        
        <li class="menu-item menu-item-home">
          <a href="/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-home"></i> <br />
            
            首页
          </a>
        </li>
      
        
        <li class="menu-item menu-item-tech-stack">
          <a href="/tech-stack" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-balance-scale"></i> <br />
            
            技术栈
          </a>
        </li>
      
        
        <li class="menu-item menu-item-holzwege">
          <a href="/holzwege" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-tripadvisor"></i> <br />
            
            林中路
          </a>
        </li>
      
        
        <li class="menu-item menu-item-on-earth">
          <a href="/on-earth" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-empire"></i> <br />
            
            人间事
          </a>
        </li>
      
        
        <li class="menu-item menu-item-about">
          <a href="/about" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-user-secret"></i> <br />
            
            关于我
          </a>
        </li>
      

      
        <li class="menu-item menu-item-search">
          
            <a href="javascript:;" class="popup-trigger">
          
            
              <i class="menu-item-icon fa fa-search fa-fw"></i> <br />
            
            搜一下
          </a>
        </li>
      
    </ul>
  

  
    <div class="site-search">
      
  <div class="popup">
 <span class="search-icon fa fa-search"></span>
 <input type="text" id="local-search-input" placeholder="search my blog...">
 <div id="local-search-result"></div>
 <span class="popup-btn-close">close</span>
</div>


    </div>
  

</nav>


 </div>
    </header>

    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    

  

  
  
  

  <article class="post post-type-normal " itemscope itemtype="http://schema.org/Article">
  <link itemprop="mainEntityOfPage" href="http://yoursite.com/2017/08/25/Java学习笔记（6）：异常处理/">

  <span style="display:none" itemprop="author" itemscope itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Free Will">
    <meta itemprop="description" content="">
    <meta itemprop="image" content="/img/v.png">
  </span>

  <span style="display:none" itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
    <meta itemprop="name" content="Free Will">
    <span style="display:none" itemprop="logo" itemscope itemtype="http://schema.org/ImageObject">
      <img style="display:none;" itemprop="url image" alt="Free Will" src="">
    </span>
  </span>

    
      <header class="post-header">

        
        
          <h1 class="post-title" itemprop="name headline">
            
            
              
                Java学习笔记（6）：异常处理
              
            
          </h1>
        

        <div class="post-meta">
          <span class="post-time">
            
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              <span class="post-meta-item-text">发表于</span>
              <time title="Post created" itemprop="dateCreated datePublished" datetime="2017-08-25T22:20:45+08:00">
                2017-08-25
              </time>
            

            

            
          </span>

          
            <span class="post-category" >
              <span class="post-meta-divider">|</span>
              <span class="post-meta-item-icon">
                <i class="fa fa-folder-o"></i>
              </span>
              <span class="post-meta-item-text">分类于</span>
              
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/categories/Java/" itemprop="url" rel="index">
                    <span itemprop="name">Java</span>
                  </a>
                </span>

                
                
              
            </span>
          

          
            
          

          

          
          

          
            <span class="post-meta-divider">|</span>
            <span class="page-pv"><i class="fa fa-eye"></i>
            <span class="busuanzi-value" id="busuanzi_value_page_pv" ></span>
            </span>
          

          

        </div>
      </header>
    


    <div class="post-body" itemprop="articleBody">

      
      

      
        <h1 id="一、异常处理基础"><a href="#一、异常处理基础" class="headerlink" title="一、异常处理基础"></a>一、异常处理基础</h1><p>Java异常是一个描述在代码段中发生的异常（也就是出错）情况的对象。当异常情况发生，一个代表该异常的对象被创建并且在导致该错误的方法中被抛出（throw）。该方法可以选择自己处理异常或传递该异常。两种情况下，该异常被捕获（catch）并处理。异常可能是由Java运行时系统产生，或者是由你的手工代码产生。被Java抛出的异常与违反语言规范或超出Java执行环境限制的基本错误有关。手工编码产生的异常基本上用于报告方法调用程序的出错状况。</p>
<a id="more"></a>
<p>Java异常处理通过5个关键字控制：try、catch、throw、throws和 finally。下面讲述它们如何工作的。程序声明了你想要的异常监控包含在一个try块中。如果在try块中发生异常，它被抛出。你的代码可以捕捉这个异常（用catch）并且用某种合理的方法处理该异常。系统产生的异常被Java运行时系统自动抛出。手动抛出一个异常，用关键字throw。任何被抛出方法的异常都必须通过throws子句定义。任何在方法返回前绝对被执行的代码被放置在finally块中。</p>
<p>下面是一个异常处理块的通常形式：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div></pre></td><td class="code"><pre><div class="line">try&#123;</div><div class="line">    // block of code to monitor for errors</div><div class="line">&#125;</div><div class="line">catch (ExceptionType1 exOb) &#123;</div><div class="line">    // exception handler for ExceptionType1</div><div class="line">&#125;</div><div class="line">catch (ExceptionType2 exOb) &#123;</div><div class="line">    // exception handler for ExceptionType2</div><div class="line">&#125;</div><div class="line">// ...</div><div class="line">finally &#123;</div><div class="line">    // block of code to be executed before try block ends</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>这里，ExceptionType 是发生异常的类型。下面将介绍怎样应用这个框架。</p>
<h1 id="二、异常类型"><a href="#二、异常类型" class="headerlink" title="二、异常类型"></a>二、异常类型</h1><p>所有异常类型都是内置类Throwable的子类。因此，Throwable在异常类层次结构的顶层。紧接着Throwable下面的是两个把异常分成两个不同分支的子类。一个分支是Exception。该类用于用户程序可能捕捉的异常情况。它也是你可以用来创建你自己用户异常类型子类的类。在Exception分支中有一个重要子类RuntimeException。该类型的异常自动为你所编写的程序定义并且包括被零除和非法数组索引这样的错误。</p>
<p>另一类分支由Error作为顶层，Error定义了在通常环境下不希望被程序捕获的异常。Error类型的异常用于Java运行时系统来显示与运行时系统本身有关的错误。堆栈溢出是这种错误的一例。本章将不讨论关于Error类型的异常处理，因为它们通常是灾难性的致命错误，不是你的程序可以控制的。</p>
<h1 id="三、未被捕获的异常"><a href="#三、未被捕获的异常" class="headerlink" title="三、未被捕获的异常"></a>三、未被捕获的异常</h1><p>在你学习在程序中处理异常之前，看一看如果你不处理它们会有什么情况发生是很有好处的。下面的小程序包括一个故意导致被零除错误的表达式。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div></pre></td><td class="code"><pre><div class="line">class Exc0 &#123;</div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">        int d = 0;</div><div class="line">        int a = 42 / d;</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>当Java运行时系统检查到被零除的情况，它构造一个新的异常对象然后抛出该异常。这导致Exc0的执行停止，因为一旦一个异常被抛出，它必须被一个异常处理程序捕获并且被立即处理。该例中，我们没有提供任何我们自己的异常处理程序，所以异常被Java运行时系统的默认处理程序捕获。任何不是被你程序捕获的异常最终都会被该默认处理程序处理。默认处理程序显示一个描述异常的字符串，打印异常发生处的堆栈轨迹并且终止程序。</p>
<p>下面是由标准javaJDK运行时解释器执行该程序所产生的输出：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">java.lang.ArithmeticException: / by zero</div><div class="line">at Exc0.main(Exc0.java:4)</div></pre></td></tr></table></figure>
<p>注意，类名Exc0，方法名main，文件名Exc0.java和行数4是怎样被包括在一个简单的堆栈使用轨迹中的。还有，注意抛出的异常类型是Exception的一个名为ArithmeticException的子类，该子类更明确的描述了何种类型的错误方法。本章后面部分将讨论，Java提供多个内置的与可能产生的不同种类运行时错误相匹配的异常类型。</p>
<p>堆栈轨迹将显示导致错误产生的方法调用序列。例如，下面是前面程序的另一个版本，它介绍了相同的错误，但是错误是在main( )方法之外的另一个方法中产生的：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div></pre></td><td class="code"><pre><div class="line">class Demo &#123;</div><div class="line">    static void subroutine() &#123;</div><div class="line">        int d = 0;</div><div class="line">        int a = 10 / d;</div><div class="line">    &#125;</div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">        Exc1.subroutine();</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>默认异常处理器的堆栈轨迹结果表明了整个调用栈是怎样显示的：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line">java.lang.ArithmeticException: / by zero</div><div class="line">at Exc1.subroutine(Exc1.java:4)</div><div class="line">at Exc1.main(Exc1.java:7)</div></pre></td></tr></table></figure>
<p>如你所见，栈底是main的第7行，该行调用了subroutine( )方法。该方法在第4行导致了异常。调用堆栈对于调试来说是很重要的，因为它查明了导致错误的精确的步骤。</p>
<h1 id="四、try和catch的使用"><a href="#四、try和catch的使用" class="headerlink" title="四、try和catch的使用"></a>四、try和catch的使用</h1><p>尽管由Java运行时系统提供的默认异常处理程序对于调试是很有用的，但通常你希望自己处理异常。这样做有两个好处。第一，它允许你修正错误。第二，它防止程序自动终止。大多数用户对于在程序终止运行和在无论何时错误发生都会打印堆栈轨迹感到很烦恼（至少可以这么说）。幸运的是，这很容易避免。为防止和处理一个运行时错误，只需要把你所要监控的代码放进一个try块就可以了。紧跟着try块的，包括一个说明你希望捕获的错误类型的catch子句。完成这个任务很简单，下面的程序包含一个处理因为被零除而产生的ArithmeticException 异常的try块和一个catch子句。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div></pre></td><td class="code"><pre><div class="line">class Demo &#123;</div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">        int d, a;</div><div class="line">        try &#123; // monitor a block of code.</div><div class="line">            d = 0;</div><div class="line">            a = 42 / d;</div><div class="line">            System.out.println(&quot;This will not be printed.&quot;);</div><div class="line">        &#125; catch (ArithmeticException e) &#123; // catch divide-by-zero error</div><div class="line">            System.out.println(&quot;Division by zero.&quot;);</div><div class="line">        &#125;</div><div class="line">        System.out.println(&quot;After catch statement.&quot;);</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>该程序输出如下：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">Division by zero.</div><div class="line">After catch statement.</div></pre></td></tr></table></figure>
<p>注意在try块中的对println( )的调用是永远不会执行的。一旦异常被引发，程序控制由try块转到catch块。执行永远不会从catch块“返回”到try块。因此，“This will not be printed。”将不会被显示。一旦执行了catch语句，程序控制从整个try/catch机制的下面一行继续。</p>
<p>一个try和它的catch语句形成了一个单元。catch子句的范围限制于try语句前面所定义的语句。一个catch语句不能捕获另一个try声明所引发的异常（除非是嵌套的try语句情况）。</p>
<p>被try保护的语句声明必须在一个大括号之内（也就是说，它们必须在一个块中）。你不能单独使用try。</p>
<p>构造catch子句的目的是解决异常情况并且像错误没有发生一样继续运行。例如，下面的程序中，每一个for循环的反复得到两个随机整数。这两个整数分别被对方除，结果用来除12345。最后的结果存在a中。如果一个除法操作导致被零除错误，它将被捕获，a的值设为零，程序继续运行。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div></pre></td><td class="code"><pre><div class="line">//Handle an exception and move on.</div><div class="line">import java.util.Random;</div><div class="line"></div><div class="line">class Demo &#123;</div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">        int a=0, b=0, c=0;</div><div class="line">        Random r = new Random();</div><div class="line"></div><div class="line">        for(int i=0; i&lt;30; i++) &#123;</div><div class="line">            try &#123;</div><div class="line">                b = r.nextInt();</div><div class="line">                c = r.nextInt();</div><div class="line">                a = 12345 / (b/c);</div><div class="line">            &#125; catch (ArithmeticException e) &#123;</div><div class="line">                System.out.println(&quot;Division by zero.&quot;);</div><div class="line">                a = 0; // set a to zero and continue</div><div class="line">            &#125;</div><div class="line">            System.out.println(&quot;a: &quot; + a);</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>Throwable重载toString( )方法（由Object定义），所以它返回一个包含异常描述的字符串。你可以通过在println( )中传给异常一个参数来显示该异常的描述。例如，前面程序的catch块可以被重写成</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div></pre></td><td class="code"><pre><div class="line">//Handle an exception and move on.</div><div class="line">import java.util.Random;</div><div class="line"></div><div class="line">class Demo &#123;</div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">        int a=0, b=0, c=0;</div><div class="line">        Random r = new Random();</div><div class="line"></div><div class="line">        for(int i=0; i&lt;30; i++) &#123;</div><div class="line">            try &#123;</div><div class="line">                b = r.nextInt();</div><div class="line">                c = r.nextInt();</div><div class="line">                a = 12345 / (b/c);</div><div class="line">            &#125; catch (ArithmeticException e) &#123;</div><div class="line">            	System.out.println(&quot;Exception: &quot; + e);</div><div class="line">            	a = 0; // set a to zero and continue</div><div class="line">            	&#125;</div><div class="line">            System.out.println(&quot;a: &quot; + a);</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>当这个版本代替原程序中的版本，程序在标准javaJDK解释器下运行，每一个被零除错误显示下面的消息：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div></pre></td><td class="code"><pre><div class="line">Exception: java.lang.ArithmeticException: / by zero</div></pre></td></tr></table></figure>
<p>尽管在上下文中没有特殊的值，显示一个异常描述的能力在其他情况下是很有价值的——特别是当你对异常进行实验和调试时。</p>
<h1 id="五、多重catch语句的使用"><a href="#五、多重catch语句的使用" class="headerlink" title="五、多重catch语句的使用"></a>五、多重catch语句的使用</h1><p>某些情况，由单个代码段可能引起多个异常。处理这种情况，你可以定义两个或更多的catch子句，每个子句捕获一种类型的异常。当异常被引发时，每一个catch子句被依次检查，第一个匹配异常类型的子句执行。当一个catch语句执行以后，其他的子句被旁路，执行从try/catch块以后的代码开始继续。下面的例子设计了两种不同的异常类型：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div></pre></td><td class="code"><pre><div class="line">//Demonstrate multiple catch statements.</div><div class="line">class Demo &#123;</div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">        try &#123;</div><div class="line">            int a = args.length;</div><div class="line">            System.out.println(&quot;a = &quot; + a);</div><div class="line">            int b = 42 / a;</div><div class="line">            int c[] = &#123; 1 &#125;;</div><div class="line">            c[42] = 99;</div><div class="line">        &#125; catch(ArithmeticException e) &#123;</div><div class="line">            System.out.println(&quot;Divide by 0: &quot; + e);</div><div class="line">        &#125; catch(ArrayIndexOutOfBoundsException e) &#123;</div><div class="line">            System.out.println(&quot;Array index oob: &quot; + e);</div><div class="line">        &#125;</div><div class="line">        System.out.println(&quot;After try/catch blocks.&quot;);</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>该程序在没有命令行参数的起始条件下运行导致被零除异常，因为a为0。如果你提供一个命令行参数，它将幸免于难，把a设成大于零的数值。但是它将导致ArrayIndexOutOf BoundsException异常，因为整型数组c的长度为1，而程序试图给c[42]赋值。下面是运行在两种不同情况下程序的输出：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div></pre></td><td class="code"><pre><div class="line">C:\&gt;java MultiCatch</div><div class="line">a = 0</div><div class="line">Divide by 0: java.lang.ArithmeticException: / by zero After try/catch blocks.</div><div class="line">C:\&gt;java MultiCatch TestArg</div><div class="line">a = 1</div><div class="line">Array index oob: java.lang.ArrayIndexOutOfBoundsException After try/catch blocks.</div></pre></td></tr></table></figure>
<p>当你用多catch语句时，记住异常子类必须在它们任何父类之前使用是很重要的。这是因为运用父类的catch语句将捕获该类型及其所有子类类型的异常。这样，如果子类在父类后面，子类将永远不会到达。而且，Java中不能到达的代码是一个错误。例如，考虑下面的程序：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div></pre></td><td class="code"><pre><div class="line">//This program contains an error.</div><div class="line">//A subclass must come before its superclass in a series of catch statements. If not,unreachable code will be created and acompile-time error will result.</div><div class="line">//*/</div><div class="line">class Demo &#123;</div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">        try &#123;</div><div class="line">            int a = 0;</div><div class="line">            int b = 42 / a;</div><div class="line">        &#125; catch(Exception e) &#123;</div><div class="line">            System.out.println(&quot;Generic Exception catch.&quot;);</div><div class="line">        &#125;</div><div class="line">        /* This catch is never reached because</div><div class="line">        ArithmeticException is a subclass of Exception. */</div><div class="line">        catch(ArithmeticException e) &#123; // ERROR - unreachable</div><div class="line">            System.out.println(&quot;This is never reached.&quot;);</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>如果你试着编译该程序，你会收到一个错误消息，该错误消息说明第二个catch语句不会到达，因为该异常已经被捕获。因为ArithmeticException 是Exception的子类，第一个catch语句将处理所有的面向Exception的错误，包括ArithmeticException。这意味着第二个catch语句永远不会执行。为修改程序，颠倒两个catch语句的次序。</p>
<h1 id="六、try语句的嵌套"><a href="#六、try语句的嵌套" class="headerlink" title="六、try语句的嵌套"></a>六、try语句的嵌套</h1><p>Try语句可以被嵌套。也就是说，一个try语句可以在另一个try块内部。每次进入try语句，异常的前后关系都会被推入堆栈。如果一个内部的try语句不含特殊异常的catch处理程序，堆栈将弹出，下一个try语句的catch处理程序将检查是否与之匹配。这个过程将继续直到一个catch语句匹配成功，或者是直到所有的嵌套try语句被检查耗尽。如果没有catch语句匹配，Java的运行时系统将处理这个异常。下面是运用嵌套try语句的一个例子：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div><div class="line">24</div></pre></td><td class="code"><pre><div class="line">//An example of nested try statements.</div><div class="line">class Demo &#123;</div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">        try &#123;</div><div class="line">            int a = args.length;</div><div class="line">            /* If no command-line args are present,the following statement will generate a divide-by-zero exception. */</div><div class="line">            int b = 42 / a;</div><div class="line">            System.out.println(&quot;a = &quot; + a);</div><div class="line">            try &#123; // nested try block</div><div class="line">                /* If one command-line arg is used,then a divide-by-zero exception will be generated by the following code. */</div><div class="line">                if(a==1) a = a/(a-a); // division by zero</div><div class="line">                /* If two command-line args are used,then generate an out-of-bounds exception. */</div><div class="line">                if(a==2) &#123;</div><div class="line">                    int c[] = &#123; 1 &#125;;</div><div class="line">                    c[42] = 99; // generate an out-of-bounds exception</div><div class="line">                &#125;</div><div class="line">            &#125; catch(ArrayIndexOutOfBoundsException e) &#123;</div><div class="line">                System.out.println(&quot;Array index out-of-bounds: &quot; + e);</div><div class="line">            &#125;</div><div class="line">        &#125; catch(ArithmeticException e) &#123;</div><div class="line">            System.out.println(&quot;Divide by 0: &quot; + e);</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>如你所见，该程序在一个try块中嵌套了另一个try块。程序工作如下：当你在没有命令行参数的情况下执行该程序，外面的try块将产生一个被零除的异常。程序在有一个命令行参数条件下执行，由嵌套的try块产生一个被零除的错误。因为内部的块不匹配这个异常，它将把异常传给外部的try块，在那里异常被处理。如果你在具有两个命令行参数的条件下执行该程序，由内部try块产生一个数组边界异常。下面的结果阐述了每一种情况：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div></pre></td><td class="code"><pre><div class="line">C:\&gt;java NestTry</div><div class="line">Divide by 0: java.lang.ArithmeticException: / by zero</div><div class="line">C:\&gt;java NestTry One</div><div class="line">a = 1</div><div class="line">Divide by 0: java.lang.ArithmeticException: / by zero</div><div class="line">C:\&gt;java NestTry One Two</div><div class="line">a = 2</div><div class="line">Array index out-of-bounds: java.lang.ArrayIndexOutOfBoundsException</div></pre></td></tr></table></figure>
<p>当有方法调用时，try语句的嵌套可以很隐蔽的发生。例如，你可以把对方法的调用放在一个try块中。在该方法内部，有另一个try语句。这种情况下，方法内部的try仍然是嵌套在外部调用该方法的try块中的。下面是前面例子的修改，嵌套的try块移到了方法nesttry( )的内部：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div><div class="line">24</div><div class="line">25</div><div class="line">26</div><div class="line">27</div><div class="line">28</div></pre></td><td class="code"><pre><div class="line">//Try statements can be implicitly nested via calls to methods. */</div><div class="line">class Demo &#123;</div><div class="line">    static void nesttry(int a) &#123;</div><div class="line">        try &#123; // nested try block</div><div class="line">            /* If one command-line arg is used,then a divide-by-zero exception will be generated by the following code. */</div><div class="line">            if(a==1) a = a/(a-a); // division by zero</div><div class="line">            /* If two command-line args are used,then generate an out-of-bounds exception. */</div><div class="line">            if(a==2) &#123;</div><div class="line">                int c[] = &#123; 1 &#125;;</div><div class="line">                c[42] = 99; // generate an out-of-bounds exception</div><div class="line">            &#125;</div><div class="line">        &#125; catch(ArrayIndexOutOfBoundsException e) &#123;</div><div class="line">            System.out.println(&quot;Array index out-of-bounds: &quot; + e);</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line"></div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">        try &#123;</div><div class="line">            int a = args.length;</div><div class="line">           /* If no command-line args are present,the following statement will generate a divide-by-zero exception. */</div><div class="line">           int b = 42 / a;</div><div class="line">           System.out.println(&quot;a = &quot; + a);</div><div class="line">           nesttry(a);</div><div class="line">        &#125; catch(ArithmeticException e) &#123;</div><div class="line">            System.out.println(&quot;Divide by 0: &quot; + e);</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>该程序的输出与前面的例子相同。</p>
<h1 id="八、throws子句"><a href="#八、throws子句" class="headerlink" title="八、throws子句"></a>八、throws子句</h1><p>如果一个方法可以导致一个异常但不处理它，它必须指定这种行为以使方法的调用者可以保护它们自己而不发生异常。做到这点你可以在方法声明中包含一个throws子句。一个 throws 子句列举了一个方法可能抛出的所有异常类型。这对于除Error或RuntimeException及它们子类以外类型的所有异常是必要的。一个方法可以抛出的所有其他类型的异常必须在throws子句中声明。如果不这样做，将会导致编译错误。</p>
<p>下面是包含一个throws子句的方法声明的通用形式：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line">type method-name(parameter-list) throws exception-list&#123;</div><div class="line">    // body of method</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>这里，exception-list是该方法可以抛出的以有逗号分割的异常列表。</p>
<p>下面是一个不正确的例子。该例试图抛出一个它不能捕获的异常。因为程序没有指定一个throws子句来声明这一事实，程序将不会编译。<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div></pre></td><td class="code"><pre><div class="line">//this program contains an error and will not compile.</div><div class="line">class ThrowsDemo &#123;</div><div class="line">    static void throwOne() &#123;</div><div class="line">        System.out.println(&quot;Inside throwOne.&quot;);</div><div class="line">        throw new IllegalAccessException(&quot;demo&quot;);</div><div class="line">    &#125;</div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">        throwOne();</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure></p>
<p>为编译该程序，需要改变两个地方。第一，需要声明throwOne( )引发IllegalAccess Exception异常。第二，main( )必须定义一个try/catch 语句来捕获该异常。正确的例子如下：<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div></pre></td><td class="code"><pre><div class="line">//This is now correct.</div><div class="line">class Demo &#123;</div><div class="line">    static void throwOne() throws IllegalAccessException &#123;</div><div class="line">      System.out.println(&quot;Inside throwOne.&quot;);</div><div class="line">      throw new IllegalAccessException(&quot;demo&quot;);</div><div class="line">   &#125;</div><div class="line">   public static void main(String args[]) &#123;</div><div class="line">      try &#123;</div><div class="line">         throwOne();</div><div class="line">      &#125; catch (IllegalAccessException e) &#123;</div><div class="line">         System.out.println(&quot;Caught &quot; + e);</div><div class="line">      &#125;</div><div class="line">   &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure></p>
<p>下面是例题的输出结果：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">inside throwOne</div><div class="line">caught java.lang.IllegalAccessException: demo</div></pre></td></tr></table></figure>
<h1 id="九、finally块"><a href="#九、finally块" class="headerlink" title="九、finally块"></a>九、finally块</h1><p>当异常被抛出，通常方法的执行将作一个陡峭的非线性的转向。依赖于方法是怎样编码的，异常甚至可以导致方法过早返回。这在一些方法中是一个问题。例如，如果一个方法打开一个文件项并关闭，然后退出，你不希望关闭文件的代码被异常处理机制旁路。finally关键字为处理这种意外而设计。finally创建一个代码块。该代码块在一个try/catch 块完成之后另一个try/catch出现之前执行。finally块无论有没有异常抛出都会执行。如果异常被抛出，finally甚至是在没有与该异常相匹配的catch子句情况下也将执行。一个方法将从一个try/catch块返回到调用程序的任何时候，经过一个未捕获的异常或者是一个明确的返回语句，finally子句在方法返回之前仍将执行。这在关闭文件句柄和释放任何在方法开始时被分配的其他资源是很有用的。finally子句是可选项，可以有也可以无。然而每一个try语句至少需要一个catch或finally子句。</p>
<p>下面的例子显示了3种不同的退出方法。每一个都执行了finally子句：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div><div class="line">24</div><div class="line">25</div><div class="line">26</div><div class="line">27</div><div class="line">28</div><div class="line">29</div><div class="line">30</div><div class="line">31</div><div class="line">32</div><div class="line">33</div><div class="line">34</div><div class="line">35</div><div class="line">36</div><div class="line">37</div><div class="line">38</div><div class="line">39</div><div class="line">40</div></pre></td><td class="code"><pre><div class="line"><span class="comment">//Demonstrate finally.</span></div><div class="line"><span class="class"><span class="keyword">class</span> <span class="title">Demo</span> </span>&#123;</div><div class="line">    <span class="comment">// Through an exception out of the method.</span></div><div class="line">    <span class="function"><span class="keyword">static</span> <span class="keyword">void</span> <span class="title">procA</span><span class="params">()</span> </span>&#123;</div><div class="line">        <span class="keyword">try</span> &#123;</div><div class="line">           System.out.println(<span class="string">"inside procA"</span>);</div><div class="line">           <span class="keyword">throw</span> <span class="keyword">new</span> RuntimeException(<span class="string">"demo"</span>);</div><div class="line">        &#125; <span class="keyword">finally</span> &#123;</div><div class="line">           System.out.println(<span class="string">"procA's finally"</span>);</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line"></div><div class="line">    <span class="comment">// Return from within a try block.</span></div><div class="line">    <span class="function"><span class="keyword">static</span> <span class="keyword">void</span> <span class="title">procB</span><span class="params">()</span> </span>&#123;</div><div class="line">        <span class="keyword">try</span> &#123;</div><div class="line">           System.out.println(<span class="string">"inside procB"</span>);</div><div class="line">           <span class="keyword">return</span>;</div><div class="line">        &#125; <span class="keyword">finally</span> &#123;</div><div class="line">           System.out.println(<span class="string">"procB's finally"</span>);</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">    <span class="comment">// Execute a try block normally.</span></div><div class="line">    <span class="function"><span class="keyword">static</span> <span class="keyword">void</span> <span class="title">procC</span><span class="params">()</span> </span>&#123;</div><div class="line">        <span class="keyword">try</span> &#123;</div><div class="line">           System.out.println(<span class="string">"inside procC"</span>);</div><div class="line">        &#125; <span class="keyword">finally</span> &#123;</div><div class="line">           System.out.println(<span class="string">"procC's finally"</span>);</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line"></div><div class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String args[])</span> </span>&#123;</div><div class="line">       <span class="keyword">try</span> &#123;</div><div class="line">          procA();</div><div class="line">       &#125; <span class="keyword">catch</span> (Exception e) &#123;</div><div class="line">          System.out.println(<span class="string">"Exception caught"</span>);</div><div class="line">       &#125;</div><div class="line">       procB();</div><div class="line">       procC();</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>该例中，procA( )过早地通过抛出一个异常中断了try。Finally子句在退出时执行。procB( )的try语句通过一个return语句退出。在procB( )返回之前finally子句执行。在procC（）中，try语句正常执行，没有错误。然而，finally块仍将执行。</p>
<p>注意：如果finally块与一个try联合使用，finally块将在try结束之前执行。</p>
<p>下面是上述程序产生的输出：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div></pre></td><td class="code"><pre><div class="line">inside procA</div><div class="line">procA’s finally</div><div class="line">Exception caught</div><div class="line">inside procB</div><div class="line">procB’s finally</div><div class="line">inside procC</div><div class="line">procC’s finally</div></pre></td></tr></table></figure>
<h1 id="十、内置异常"><a href="#十、内置异常" class="headerlink" title="十、内置异常"></a>十、内置异常</h1><p>在标准包java.lang中，Java定义了若干个异常类。前面的例子曾用到其中一些。这些异常一般是标准类RuntimeException的子类。因为java.lang实际上被所有的Java程序引入，多数从RuntimeException派生的异常都自动可用。而且，它们不需要被包含在任何方法的throws列表中。Java语言中，这被叫做未经检查的异常（unchecked exceptions ）。因为编译器不检查它来看一个方法是否处理或抛出了这些异常。 java.lang中定义的未经检查的异常列于表10-1。表10-2列出了由 java.lang定义的必须在方法的throws列表中包括的异常，如果这些方法能产生其中的某个异常但是不能自己处理它。这些叫做受检查的异常（checked exceptions）。Java定义了几种与不同类库相关的其他的异常类型。</p>
<blockquote>
<p>Java 的 java.lang 中定义的未检查异常子类</p>
</blockquote>
<div class="table-container">
<table>
<thead>
<tr>
<th>异常</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>ArithmeticException</td>
<td>算术错误，如被0除</td>
</tr>
<tr>
<td>ArrayIndexOutOfBoundsException</td>
<td>数组下标出界</td>
</tr>
<tr>
<td>ArrayStoreException</td>
<td>数组元素赋值类型不兼容</td>
</tr>
<tr>
<td>ClassCastException</td>
<td>非法强制转换类型</td>
</tr>
<tr>
<td>IllegalArgumentException</td>
<td>调用方法的参数非法</td>
</tr>
<tr>
<td>IllegalMonitorStateException</td>
<td>非法监控操作，如等待一个未锁定线程</td>
</tr>
<tr>
<td>IllegalStateException</td>
<td>环境或应用状态不正确</td>
</tr>
<tr>
<td>IllegalThreadStateException</td>
<td>请求操作与当前线程状态不兼容</td>
</tr>
<tr>
<td>IndexOutOfBoundsException</td>
<td>某些类型索引越界</td>
</tr>
<tr>
<td>NullPointerException</td>
<td>非法使用空引用</td>
</tr>
<tr>
<td>NumberFormatException</td>
<td>字符串到数字格式非法转换</td>
</tr>
<tr>
<td>SecurityException</td>
<td>试图违反安全性</td>
</tr>
<tr>
<td>StringIndexOutOfBounds</td>
<td>试图在字符串边界之外索引</td>
</tr>
<tr>
<td>UnsupportedOperationException</td>
<td>遇到不支持的操作</td>
</tr>
</tbody>
</table>
</div>
<blockquote>
<p> java.lang 中定义的检查异常</p>
</blockquote>
<div class="table-container">
<table>
<thead>
<tr>
<th>异常</th>
<th>意义</th>
</tr>
</thead>
<tbody>
<tr>
<td>ClassNotFoundException</td>
<td>找不到类</td>
</tr>
<tr>
<td>CloneNotSupportedException</td>
<td>试图克隆一个不能实现Cloneable接口的对象</td>
</tr>
<tr>
<td>IllegalAccessException</td>
<td>对一个类的访问被拒绝</td>
</tr>
<tr>
<td>InstantiationException</td>
<td>试图创建一个抽象类或者抽象接口的对象</td>
</tr>
<tr>
<td>InterruptedException</td>
<td>一个线程被另一个线程中断</td>
</tr>
<tr>
<td>NoSuchFieldException</td>
<td>请求的字段不存在</td>
</tr>
<tr>
<td>NoSuchMethodException</td>
<td>请求的方法不存在</td>
</tr>
</tbody>
</table>
</div>
<h1 id="十一、创建自己的异常子类"><a href="#十一、创建自己的异常子类" class="headerlink" title="十一、创建自己的异常子类"></a>十一、创建自己的异常子类</h1><p>尽管Java的内置异常处理大多数常见错误，你也许希望建立你自己的异常类型来处理你所应用的特殊情况。这是非常简单的：只要定义Exception的一个子类就可以了（Exception当然是Throwable的一个子类）。你的子类不需要实际执行什么——它们在类型系统中的存在允许你把它们当成异常使用。Exception类自己没有定义任何方法。当然，它继承了Throwable提供的一些方法。因此，所有异常，包括你创建的，都可以获得Throwable定义的方法。这些方法显示在表10-3中。你还可以在你创建的异常类中覆盖一个或多个这样的方法。</p>
<blockquote>
<p>Throwable 定义的方法</p>
</blockquote>
<div class="table-container">
<table>
<thead>
<tr>
<th>方法</th>
<th>描述</th>
</tr>
</thead>
<tbody>
<tr>
<td>Throwable fillInStackTrace( )</td>
<td>返回一个包含完整堆栈轨迹的Throwable对象，该对象可能被再次引发。</td>
</tr>
<tr>
<td>String getLocalizedMessage( )</td>
<td>返回一个异常的局部描述</td>
</tr>
<tr>
<td>String getMessage( )</td>
<td>返回一个异常的描述</td>
</tr>
<tr>
<td>void printStackTrace( )</td>
<td>显示堆栈轨迹</td>
</tr>
<tr>
<td>void printStackTrace(PrintStreamstream)</td>
<td>把堆栈轨迹送到指定的流</td>
</tr>
<tr>
<td>void printStackTrace(PrintWriterstream)</td>
<td>把堆栈轨迹送到指定的流</td>
</tr>
<tr>
<td>String toString( )</td>
<td>返回一个包含异常描述的String对象。当输出一个Throwable对象时，该方法被println( )调用</td>
</tr>
</tbody>
</table>
</div>
<p>下面的例子声明了Exception的一个新子类，然后该子类当作方法中出错情形的信号。它重载了toString( )方法，这样可以用println( )显示异常的描述。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div><div class="line">24</div><div class="line">25</div><div class="line">26</div><div class="line">27</div><div class="line">28</div><div class="line">29</div></pre></td><td class="code"><pre><div class="line">//This program creates a custom exception type.</div><div class="line">class MyException extends Exception &#123;</div><div class="line">    private int detail;</div><div class="line">    MyException(int a) &#123;</div><div class="line">        detail = a;</div><div class="line">    &#125;</div><div class="line"></div><div class="line">    public String toString() &#123;</div><div class="line">        return &quot;MyException[&quot; + detail + &quot;]&quot;;</div><div class="line">    &#125;</div><div class="line">&#125;</div><div class="line"></div><div class="line">class ExceptionDemo &#123;</div><div class="line">    static void compute(int a) throws MyException &#123;</div><div class="line">        System.out.println(&quot;Called compute(&quot; + a + &quot;)&quot;);</div><div class="line">       if(a &gt; 10)</div><div class="line">          throw new MyException(a);</div><div class="line">       System.out.println(&quot;Normal exit&quot;);</div><div class="line">    &#125;</div><div class="line"></div><div class="line">    public static void main(String args[]) &#123;</div><div class="line">       try &#123;</div><div class="line">           compute(1);</div><div class="line">           compute(20);</div><div class="line">        &#125; catch (MyException e) &#123;</div><div class="line">            System.out.println(&quot;Caught &quot; + e);</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>该例题定义了Exception的一个子类MyException。该子类非常简单：它只含有一个构造函数和一个重载的显示异常值的toString( )方法。ExceptionDemo类定义了一个compute( )方法。该方法抛出一个MyException对象。当compute( )的整型参数比10大时该异常被引发。</p>
<p>main( )方法为MyException设立了一个异常处理程序，然后用一个合法的值和不合法的值调用compute( )来显示执行经过代码的不同路径。下面是结果：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div></pre></td><td class="code"><pre><div class="line">Called compute(1)</div><div class="line">Normal exit</div><div class="line">Called compute(20)</div><div class="line">Caught MyException[20]</div></pre></td></tr></table></figure>
<h1 id="十二、断言"><a href="#十二、断言" class="headerlink" title="十二、断言"></a>十二、断言</h1><p>断言用于证明和测试程序的假设，比如“这里的值大于 5”。<br>断言可以在运行时从代码中完全删除，所以对代码的运行速度没有影响。</p>
<p>断言有两种方法：</p>
<ul>
<li>一种是 assert&lt;&lt;布尔表达式&gt;&gt; ；</li>
<li>另一种是 assert&lt;&lt;布尔表达式&gt;&gt; ：&lt;&lt;细节描述&gt;&gt;。</li>
</ul>
<p>如果布尔表达式的值为false ， 将抛出AssertionError 异常； 细节描述是AssertionError异常的描述文本使用 javac –source 1.4 MyClass.java 的方式进行编译示例如下：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">Demo</span> </span>&#123;</div><div class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</div><div class="line">        <span class="keyword">int</span> x = <span class="number">10</span>;</div><div class="line">        <span class="keyword">if</span> (args.length &gt; <span class="number">0</span>) &#123;</div><div class="line">            <span class="keyword">try</span> &#123;</div><div class="line">                x = Integer.parseInt(args[<span class="number">0</span>]);</div><div class="line">            &#125; <span class="keyword">catch</span> (NumberFormatException nfe) &#123;</div><div class="line">                <span class="comment">/* Ignore */</span></div><div class="line">            &#125;</div><div class="line">        &#125;</div><div class="line">        System.out.println(<span class="string">"Testing assertion that x == 10"</span>);</div><div class="line">        <span class="keyword">assert</span> x == <span class="number">10</span> : <span class="string">"Our assertion failed"</span>;</div><div class="line">        System.out.println(<span class="string">"Test passed"</span>);</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>由于引入了一个新的关键字，所以在编译的时候就需要增加额外的参数，要编译成功，必须使用 JDK1.4 的 javac 并加上参数’-source 1.4′,例如可以使用以下的命令编译上面的代码：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div></pre></td><td class="code"><pre><div class="line">javac -source 1.4 AssertExample.java</div></pre></td></tr></table></figure>
<p>以上程序运行使用断言功能也需要使用额外的参数（并且需要一个数字的命令行参数），例如：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div></pre></td><td class="code"><pre><div class="line">java -ea AssertExample 1</div></pre></td></tr></table></figure>
<p>程序的输出为：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line">Testing assertion that x == 10</div><div class="line">Exception in thread “main” java.lang.AssertionError:Our assertion failed</div><div class="line">at AssertExample.main(AssertExample.java:20)</div></pre></td></tr></table></figure>
<p>由于输入的参数不等于 10，因此断言功能使得程序运行时抛出断言错误，注意是错误， 这意味着程序发生严重错误并且将强制退出。断言使用 boolean 值，如果其值不为 true 则 抛出 AssertionError 并终止程序的运行。</p>
<p>断言推荐使用方法</p>
<p>用于验证方法中的内部逻辑，包括：</p>
<ul>
<li>内在不变式</li>
<li>控制流程不变式</li>
<li>后置条件和类不变式</li>
</ul>
<p>注意：不推荐用于公有方法内的前置条件的检查。</p>
<p>运行时要屏蔽断言，可以用如下方法：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div></pre></td><td class="code"><pre><div class="line">java –disableassertions 或 java –da 类名</div></pre></td></tr></table></figure>
<p>运行时要允许断言，可以用如下方法：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div></pre></td><td class="code"><pre><div class="line">java –enableassertions 或 java –ea类名</div></pre></td></tr></table></figure>

      
    </div>


    <div>
      
        

      
    </div>
<div>
  
    <div>
    
     <br> 
        <div style="text-align:center;color: #ccc;font-size:18px;"><br>   本文结束    <i class="fa fa-paw"></i>
             欢迎关注微信公众号【应统联盟】
       
 </div> 
        <div align="center">
<br>
        <img src="https://tva1.sinaimg.cn/large/007S8ZIlly1ggmflenudjj30kl0kmq4a.jpg" height="300" width="300"/>
        </div> <br>
        <div style="text-align:center;color: #ccc;font-size:14px;">  一个集应统考研、机器学习、知识变现、实习求职于一身的微信公众号  <br></div>
        <div>
        </div>
    
</div>
  
</div>
    <div>
      
        

      

    </div>

    <footer class="post-footer">
      
        <div class="post-tags">
          
            <a href="/tags/Java/" rel="tag"># Java</a>
          
            <a href="/tags/异常处理/" rel="tag"># 异常处理</a>
          
        </div>
      

      
        <div class="post-nav">
          <div class="post-nav-next post-nav-item">
            
              <a href="/2017/08/24/Java学习笔记（5）：static、final关键字和Object类/" rel="next" title="Java学习笔记（5）：static、final关键字和Object类">
                <i class="fa fa-chevron-left"></i> Java学习笔记（5）：static、final关键字和Object类
              </a>
            
          </div>

          <span class="post-nav-divider"></span>

          <div class="post-nav-prev post-nav-item">
            
              <a href="/2017/08/26/Java学习笔记（7）：深入理解java异常处理机制/" rel="prev" title="Java学习笔记（7）：深入理解java异常处理机制">
                Java学习笔记（7）：深入理解java异常处理机制 <i class="fa fa-chevron-right"></i>
              </a>
            
          </div>
        </div>
      

      
      
      

    </footer>
  </article>



    <div class="post-spread">
      
        <!-- Go to www.addthis.com/dashboard to customize your tools -->
<div class="addthis_inline_share_toolbox">
  <script type = "text/javascript" src = "//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5bc405fb9346cd0b" async = "async" ></script>
</div>

      
    </div>
  </div>


          </div>
          


          
  <div class="comments" id="comments">
    
  </div>


        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    
      <div id="sidebar-dimmer"></div>
    
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            文章目录
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            站点概览
          </li>
        </ul>
      

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
            
              <img class="site-author-image" itemprop="image"
                src="/img/v.png"
                alt="Free Will" />
            
              <p class="site-author-name" itemprop="name">Free Will</p>
              <p class="site-description motion-element" itemprop="description">人类被赋予了一种工作，那就是精神的成长</p>
          </div>

          <nav class="site-state motion-element">

            
              <div class="site-state-item site-state-posts">
              
                <a href="/archives">
              
                  <span class="site-state-item-count">206</span>
                  <span class="site-state-item-name">日志</span>
                </a>
              </div>
            

            
              
              
              <div class="site-state-item site-state-categories">
                <a href="/categories/index.html">
                  <span class="site-state-item-count">18</span>
                  <span class="site-state-item-name">分类</span>
                </a>
              </div>
            

            
              
              
              <div class="site-state-item site-state-tags">
                <a href="/tags/index.html">
                  <span class="site-state-item-count">308</span>
                  <span class="site-state-item-name">标签</span>
                </a>
              </div>
            

          </nav>





          <div class="links-of-author motion-element">
            
              
                <span class="links-of-author-item">
                  <a href="https://plushunter.github.io/say-sth/" target="_blank" title="絮语">
                    
                      <i class="fa fa-fw fa-heartbeat"></i>絮语</a>
                </span>
              
                <span class="links-of-author-item">
                  <a href="https://plushunter.github.io/see-movies/" target="_blank" title="电影">
                    
                      <i class="fa fa-fw fa-film"></i>电影</a>
                </span>
              
                <span class="links-of-author-item">
                  <a href="https://plushunter.github.io/competitions" target="_blank" title="竞赛">
                    
                      <i class="fa fa-fw fa-database"></i>竞赛</a>
                </span>
              
                <span class="links-of-author-item">
                  <a href="https://www.zhihu.com/people/ren-da-ying-tong-hua-qi/activities" target="_blank" title="知乎">
                    
                      <i class="fa fa-fw fa-graduation-cap"></i>知乎</a>
                </span>
              
            
          </div>
        <div id="music163player">
           <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=986476&auto=1&height=66"></iframe>
          </div>

        
          
          

          


        


          
          
            <div class="links-of-blogroll motion-element links-of-blogroll-inline">
              <div class="links-of-blogroll-title">
                <i class="fa  fa-fw fa-anchor"></i>

                扫一扫，关注微信公众号【应统联盟】
              </div>
<br><div id="sf"><img src="https://tva1.sinaimg.cn/large/007S8ZIlly1ggmflenudjj30kl0kmq4a.jpg" height="200" width="200" /></div><br>
              <ul class="links-of-blogroll-list">
                
                  <li class="links-of-blogroll-item">
                    <a href="http://www.statunion.cn" title="应统联盟 | 网站" target="_blank">应统联盟 | 网站</a>
                  </li>
                
                  <li class="links-of-blogroll-item">
                    <a href="http://statunion.club/" title="应统联盟 | 论坛" target="_blank">应统联盟 | 论坛</a>
                  </li>
                
              </ul>
            </div>

          


          

        </div>

        
        
      
  
          
      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-1"><a class="nav-link" href="#一、异常处理基础"><span class="nav-text">一、异常处理基础</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#二、异常类型"><span class="nav-text">二、异常类型</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#三、未被捕获的异常"><span class="nav-text">三、未被捕获的异常</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#四、try和catch的使用"><span class="nav-text">四、try和catch的使用</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#五、多重catch语句的使用"><span class="nav-text">五、多重catch语句的使用</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#六、try语句的嵌套"><span class="nav-text">六、try语句的嵌套</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#八、throws子句"><span class="nav-text">八、throws子句</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#九、finally块"><span class="nav-text">九、finally块</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#十、内置异常"><span class="nav-text">十、内置异常</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#十一、创建自己的异常子类"><span class="nav-text">十一、创建自己的异常子类</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#十二、断言"><span class="nav-text">十二、断言</span></a></li></ol></div>
            

          </div>

        </section>
      <!--/noindex-->
      




      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright" >
  
  &copy;  2016 - 
  <span itemprop="copyrightYear">2020</span>
  <span class="with-love">
    <i class="fa fa-heart"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Free Will</span>
</div>



        

<div class="busuanzi-count">

  <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>

	
    <span class="site-uv"><i class="fa fa-user"></i><span class="busuanzi-value" id="busuanzi_value_site_uv"></span></span>
	

	
    <span class="site-pv"><i class="fa fa-eye"></i><span class="busuanzi-value" id="busuanzi_value_site_pv"></span></span>
	
	<script src="//cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
		<script>
		    $(document).ready(function() {
		        var int = setInterval(fixCount, 100);
		        var busuanziSiteOffset_uv = parseInt(190422);
		        var busuanziSiteOffset_pv = parseInt(412128);
		        function fixCount() {
	                clearInterval(int);
	                $("#busuanzi_value_site_pv").html(parseInt($("#busuanzi_value_site_pv").html()) + busuanziSiteOffset_pv);
	                clearInterval(int);
	                $("#busuanzi_value_site_uv").html(parseInt($("#busuanzi_value_site_uv").html()) + busuanziSiteOffset_uv);
		        }
		    });
		</script>
	
	

</div>



        
      </div>
    </footer>

    <div class="back-to-top">
      <i class="fa fa-arrow-up"></i>
    </div>
  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>









  



  
  <script type="text/javascript" src="/lib/jquery/index.js?v=2.1.3"></script>

  
  <script type="text/javascript" src="/lib/fastclick/lib/fastclick.min.js?v=1.0.6"></script>

  
  <script type="text/javascript" src="/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7"></script>

  
  <script type="text/javascript" src="/lib/velocity/velocity.min.js?v=1.2.1"></script>

  
  <script type="text/javascript" src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>

  
  <script type="text/javascript" src="/lib/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>


  


  <script type="text/javascript" src="/js/src/utils.js?v=5.1.0"></script>

  <script type="text/javascript" src="/js/src/motion.js?v=5.1.0"></script>



  
  

  
  <script type="text/javascript" src="/js/src/scrollspy.js?v=5.1.0"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=5.1.0"></script>



  


  <script type="text/javascript" src="/js/src/bootstrap.js?v=5.1.0"></script>



  



  




	




  
  
  <script type="text/javascript">
    // Popup Window;
    var isfetched = false;
    // Search DB path;
    var search_path = "search.xml";
    if (search_path.length == 0) {
      search_path = "search.xml";
    }
    var path = "/" + search_path;
    // monitor main search box;

    function proceedsearch() {
      $("body").append('<div class="popoverlay">').css('overflow', 'hidden');
      $('.popup').toggle();
    }
    if (!String.prototype.endsWith) {
  String.prototype.endsWith = function(searchString, position) {
      var subjectString = this.toString();
      if (typeof position !== 'number' || !isFinite(position) || Math.floor(position) !== position || position > subjectString.length) {
        position = subjectString.length;
      }
      position -= searchString.length;
      var lastIndex = subjectString.indexOf(searchString, position);
      return lastIndex !== -1 && lastIndex === position;
  };
}
    // search function;
    var searchFunc = function(path, search_id, content_id) {
      'use strict';
      $.ajax({
        url: path,
        dataType: "xml",
        async: true,
        success: function( xmlResponse ) {
          // get the contents from search data
          isfetched = true;
          $('.popup').detach().appendTo('.header-inner');
          var datas = $( "entry", xmlResponse ).map(function() {
            return {
              title: $( "title", this ).text(),
              content: $("content",this).text(),
              url: $( "url" , this).text()
            };
          }).get();
          var $input = document.getElementById(search_id);
          var $resultContent = document.getElementById(content_id);
          $input.addEventListener('input', function(){
            var matchcounts = 0;
            var str='<ul class=\"search-result-list\">';
            var keywords = this.value.trim().toLowerCase().split(/[\s\-]+/);
            $resultContent.innerHTML = "";
            if (this.value.trim().length > 1) {
              // perform local searching
              datas.forEach(function(data) {
                var isMatch = false;
                var content_index = [];
                var data_title = data.title.trim().toLowerCase();
                var data_content = data.content.trim().replace(/<[^>]+>/g,"").toLowerCase();
                var data_url = decodeURIComponent(data.url);
                var index_title = -1;
                var index_content = -1;
                var first_occur = -1;
                // only match artiles with not empty titles and contents
                if(data_title != '') {
                  keywords.forEach(function(keyword, i) {
                    index_title = data_title.indexOf(keyword);
                    index_content = data_content.indexOf(keyword);
                    if( index_title >= 0 || index_content >= 0 ){
                      isMatch = true;
                      if (i == 0) {
                        first_occur = index_content;
                      }
                    }

                  });
                }
                // show search results
                if (isMatch) {
                  matchcounts += 1;
                  str += "<li><a href='"+ data_url +"' class='search-result-title'>"+ data_title +"</a>";
                  var content = data.content.trim().replace(/<[^>]+>/g,"");
                  if (first_occur >= 0) {
                    // cut out 100 characters
                    var start = first_occur - 20;
                    var end = first_occur + 80;
                    if(start < 0){
                      start = 0;
                    }
                    if(start == 0){
                      end = 50;
                    }
                    if(end > content.length){
                      end = content.length;
                    }
                    var match_content = content.substring(start, end);
                    // highlight all keywords
                    keywords.forEach(function(keyword){
                      var regS = new RegExp(keyword, "gi");
                      match_content = match_content.replace(regS, "<b class=\"search-keyword\">"+keyword+"</b>");
                    });

                    str += "<p class=\"search-result\">" + match_content +"...</p>"
                  }
                  str += "</li>";
                }
              })};
            str += "</ul>";
            if (matchcounts == 0) { str = '<div id="no-result"><i class="fa fa-frown-o fa-5x" /></div>' }
            if (keywords == "") { str = '<div id="no-result"><i class="fa fa-search fa-5x" /></div>' }
            $resultContent.innerHTML = str;
          });
          proceedsearch();
        }
      });}

    // handle and trigger popup window;
    $('.popup-trigger').click(function(e) {
      e.stopPropagation();
      if (isfetched == false) {
        searchFunc(path, 'local-search-input', 'local-search-result');
      } else {
        proceedsearch();
      };
    });

    $('.popup-btn-close').click(function(e){
      $('.popup').hide();
      $(".popoverlay").remove();
      $('body').css('overflow', '');
    });
    $('.popup').click(function(e){
      e.stopPropagation();
    });
  </script>


  
  
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax: {
          inlineMath: [ ['$','$'], ["\\(","\\)"]  ],
          processEscapes: true,
          skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
        }
      });
    </script>

    <script type="text/x-mathjax-config">
      MathJax.Hub.Queue(function() {
        var all = MathJax.Hub.getAllJax(), i;
        for (i=0; i < all.length; i += 1) {
          all[i].SourceElement().parentNode.className += ' has-jax';
        }
      });
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  


  

  
<script>
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https') {
        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';        
    }
    else {
        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
    }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
</script><!-- hexo-inject:begin --><!-- Begin: Injected MathJax -->
<script type="text/x-mathjax-config">
  MathJax.Hub.Config("");
</script>

<script type="text/x-mathjax-config">
  MathJax.Hub.Queue(function() {
    var all = MathJax.Hub.getAllJax(), i;
    for(i=0; i < all.length; i += 1) {
      all[i].SourceElement().parentNode.className += ' has-jax';
    }
  });
</script>

<script type="text/javascript" src="custom_mathjax_source">
</script>
<!-- End: Injected MathJax -->
<!-- hexo-inject:end -->


  


</body>
</html>
